### ISSUE TITLE
Multiple things wrong with the update

### ISSUE THREAD

**Issue by HRudyPlayZ** [hacks-guide/Guide_Vita#110]
Hey, your new update for the guide is interesting, and using VitaDeploy is a good idea, but there's a couple things wrong:

- Do not tell people on 3.60 to update to 3.73, it actually makes the process way harder than it should.
By updating to 3.73, people will have to use finalhe in order to hack their console. FinalHE is ok but still relies on Sony's CMA protocol (or more precisely the only client that works sometimes, qcma. Sony's one being so broken it almost never works fine.). FinalHE makes the hacking process way harder for 3.60 users as it requires a PC and requires much more tries to get it to work properly (thank sony for that). You could streamline the process by asking 3.60 users to use Henkaku and then VitaDeploy. VitaDeploy uses Modoru and as such, also allows for updates. Updating to 3.65 is really unnecessary but i get it, until VitaDeploys adds a Quick 3.60 button, it makes the guide easier.

- Do not hide the Henkaku method in a small banner, make it the main process since it will make things way easier and can prevent hours of troubleshooting for the end user. You can keep the 3.73 option as the secondary one, in case the Henkaku method doesn't work. 

- People below 3.60 should be redirected to a 3.60 update page, where the DNS would still be available.

- Like other users have said, you should keep a list of useful plugins inside the Finalizing page.  Even if those are installed by VitaDeploy, it can still be useful to write down.

- There's no apps that will stop supporting 3.60, at least for the end user. It would just be stupid from the dev. In fact, 3.60 tends to be the most compatible version since every plugin, the VitaSDK or homebrew apps are made with henkaku in mind, and not h-encore. Pretty much all apps will work fine between 3.60 and 3.68, but just in case, remember it is the most compatible firmware.

**Comment by emiyl** [comment]
Thank you for the feedback, I'm already considering all of the mentioned issues and I will find a solution.
