### ISSUE TITLE
"New" way for Mac and Linux people to get Hencore² & VitaDeploy

### ISSUE THREAD

**Issue by Sekoree** [hacks-guide/Guide_Vita#112]
As said on Discord, I made a small web thingy for people to get VitaShell, VitaDeploy and Hencore² (since it works on 3.65-3.73) as QCMA Backups.
https://api.vita.meek.moe/QuickLinks
The URL is a bit of pain, but it works.

Quick description on how it works:
Its essentially psvimgtools attached to a webserver
for the Account ID its using some RemotePlay URL that Chiaki also uses (https://trinket.io/embed/python3/52183a157e) but converted to C#)

**Comment by takoyaki99** [comment]
I second this to be shown somehow, it's not super well-known, but it's a good resource,

**Comment by takoyaki99** [comment]
@Sekoree is my guide that I've written for QCMA installs that I reference in my pull request up to your standards? I want to get your OK as the creator!
https://github.com/takoyaki99/Guide_Vita/blob/master/docs/installing-h-encore-(qcma).md

**Comment by lifehackerhansol** [comment]
h-encore is no longer part of the main guide path: #194
