### ISSUE TITLE
Uninstalling CFW

### ISSUE THREAD

**Issue by lunaisnotaboy** [hacks-guide/Guide_Vita#134]
Hi there,

I was wondering if there was a way to uninstall everything installed via this guide? I've looked through community resources, various applications mentioned here, and I can't seem to find anything as it was not manually installed. Is this even possible?

Thanks!

**Comment by takoyaki99** [comment]
Best I could find is an stheix video, I'll write up a guide based on it ASAP~

**Comment by takoyaki99** [comment]
Addition has been written, I hope this is satisfactory~

**Comment by lunaisnotaboy** [comment]
Thank you so much!!!
