### ISSUE TITLE
The QCMA version of installing h-encore is not integrated into site

### ISSUE THREAD

**Issue by ghost** [hacks-guide/Guide_Vita#137]
The QCMA version of installing h-encore is not included in the sidebar of the site, along with the "proceed to..." part on the bottom.
In order to make that section of the site more user-friendly, I'll make an addition to `/docs/.vuepress/configs/en_US.js` to (hopefully) rectify this. The pull request will be put into effect once my latest has been accepted in order to avoid any conflict/mistakes.

What I plan to do is:

This following section is from lines 59-72 of `en_US.js`.

```
 sidebar: {
      '/': [
        {
          text: 'Guide',
          children: [
            'index.html',
            'get-started',
            'updating-firmware-(3.73)',
            'installing-h-encore',
            'installing-enso',
            'finalizing-setup'
          ],
        },
      ],
```

What I'll add is this:

```
 sidebar: {
      '/': [
        {
          text: 'Guide',
          children: [
            'index.html',
            'get-started',
            'updating-firmware-(3.73)',
            'installing-h-encore',
            children: [
             'uninstalling-cfw.md',
              ],
            'installing-enso',
            'finalizing-setup'
          ],
        },
      ],
```

I have no idea if this'll work, but this is what I plan to do to fix this issue.

**Comment by lifehackerhansol** [comment]
h-encore is no longer part of the main guide path: #194
