### ISSUE TITLE
YAMT instructions skip from Section 1 to Section 3, skipping "2"

### ISSUE THREAD

**Issue by jordansmellie** [hacks-guide/Guide_Vita#140]
Specific to the "YAMT (SD2Vita)" page at https://vita.hacks.guide/yamt.html/ .

The instructions begin with `Section I - Installing YAMT VPK`. 
Then the next thing listed is `Section III - Formatting the microSD`.
There is no section called `Section II`; **that number gets completely skipped**.

**TO FIX IT:** Instead of the 4 sections being numbered `I / III / IV / V`, they should be renumbered `I / II / III / IV`.

**Comment by hurda** [comment]
There was PR #126 to be reviewed, but here it is.
