### ISSUE TITLE
[Q] why older firmware (1.03~3.63) must upgrade to 3.74 and not directly to 3.65?

### ISSUE THREAD

**Issue by sl1pkn07** [hacks-guide/Guide_Vita#148]
Hi

in the guide, say if you have firmware from 1.03 to 3.63, need upgrade to 3.74. but why not upgrade directly to 3.65?

i remember a method to upgrade exact fw version you want

greetings

**Comment by takoyaki99** [comment]
It's possible, but it's a bit easier to do 3.74, I guess? 

For it to be the easiest for an end user who's like "hey I have one of these in my drawer let's see what it can do after all these years" I don't think they'd like to...do weird stuff with PSP2UPDAT.PUP files over CMA or anything. Or custom DNS for that matter.

At any rate, the guide does have a section on updating directly to 3.60! It's just a lil hidden~↓
https://vita.hacks.guide/updating-firmware-(3.60).html

**Comment by emiyl** [comment]
^ this pretty much, it's just a lil simpler
