### ISSUE TITLE
Discord link at top of page sometimes disappears for no reason

### ISSUE THREAD

**Issue by lifehackerhansol** [hacks-guide/Guide_Vita#164]
For some reason, the text is just existn't. Screenshot from vita.hacks.guide/get-started: 
![image](https://github.com/hacks-guide/Guide_Vita/assets/37358975/d9f0c2a3-a33a-4c82-8c48-165746a91a95)

But local testing shows the text (screenshot from local testing):
![image](https://github.com/hacks-guide/Guide_Vita/assets/37358975/cf2f8635-e8f5-42ee-9899-0973af7299ef)

**Comment by Coolumin** [comment]
I assume this was addressed in #192 right?

**Comment by lifehackerhansol** [comment]
Yes. New theme now has a Discord invite permanently on the navigation bar, so this is no longer relevant.
