### ISSUE TITLE
Warn people to stay away from enso ex

### ISSUE THREAD

**Issue by Plausible0Bug** [hacks-guide/Guide_Vita#45]
This so called enso ex is not from original developer and can cause soft brick if SD2VITA driver provided by it is enabled.

Source: personal experience and Reddit.

**Comment by Plailect** [comment]
I don't know the details about this. Do you have some links to further info?

**Comment by Plausible0Bug** [comment]
Hi,

Sorry for not including them in the first place:

https://www.reddit.com/r/VitaPiracy/comments/b8qz2f/post_ensoex_everything_has_gone_wrong/

https://www.reddit.com/r/vitahacks/comments/b4z3ez/faq_enso_ex_v30/

**Comment by Plailect** [comment]
Ouch. Yeah I can add a sentence at the end saying to stay away from mods like that unless the user really knows what they're doing.

**Comment by Plailect** [comment]
This should stay open until it's actually fixed (otherwise I'll forget about it).
