### ISSUE TITLE
Tell people use 256GB or bigger TF card to format with 64k clusters

### ISSUE THREAD

**Issue by Plausible0Bug** [hacks-guide/Guide_Vita#48]
If formatted with default option provided by operate system, PS Vita may misread the free space and prevent save file creation even when still space available.

**Comment by Plailect** [comment]
Source?

**Comment by Plausible0Bug** [comment]
Yes sorry keep forgetting about this:
https://www.google.com/amp/s/amp.reddit.com/r/vitahacks/comments/6u9ai2/sd2vita_incorrect_free_space_solution_fix/

I also have some screenshots from my own PSV.
