### ISSUE TITLE
Provide a guide for people using SD2VITA who want to migrate to bigger SD card

### ISSUE THREAD

**Issue by Plausible0Bug** [hacks-guide/Guide_Vita#49]
Not recommend to do so on Mac OS X thanks to the stupid .DS_store contaminating every single folder.

For Windows, need to set view options to show hidden files and disable hiding of system files to see everything.

Seeing id.dat should be a good indicator view options are configured properly. Otherwise tend to lose data during transferring.

**Comment by Plailect** [comment]
This is pretty low-priority and I'm not sure this is entirely necessary as it's literally just "format the new device and copy all the files over".

**Comment by Plausible0Bug** [comment]
It is not easy to see "everything" on your SD card, though.

**Comment by Plausible0Bug** [comment]
Hi,

I can contribute to the page writing a little, if you can provide me some PR guidelines.
